import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#DAD9DE',
    paddingTop: 60,
  },
  headerContainer: {
    padding: 32,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    width: '100%',
    height: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  greetingText: {
    fontSize: 20,
    fontFamily: 'MonaSans-Regular',
  },
  headerText: {
    fontSize: 28,
    fontFamily: 'MonaSans-SemiBold',
  },
  listContainer: {
    padding: 28,
  },
  taskItem: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  priorityBar: {
    width: 4,
    backgroundColor: '#4CAF50',
  },
  taskContent: {
    flex: 1,
    padding: 16,
  },
  taskMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
    fontFamily: 'MonaSans-Medium',
  },
  taskMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryPill: {
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
  },
  categoryText: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'MonaSans-Regular',
  },
  dueText: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'MonaSans-Regular',
  },
  checkbox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#DDD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 142,
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  fabText: {
    fontSize: 40,
    color: '#333',
    marginTop: -4,
  },
  emptyText: {
    textAlign: 'center',
    color: '#666',
    fontSize: 16,
    marginTop: 24,
    fontFamily: 'MonaSans-Regular',
  },
  errorText: {
    color: '#FF3B30',
    textAlign: 'center',
    marginTop: 24,
    fontFamily: 'MonaSans-Regular',
  },
});
